[project]
name = "fehdb"
version = "0.1.0"
description = "Fire Emblem Heroes database scripts"
# readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "unidecode>=1.3.8",
]

[tool.uv]
managed = true
